variables: variables.yml
templates:
  torrent_server:
    transmission:
      host: localhost
      port: 9091
      username: "{? transmission.usr ?}"
      password: "{? transmission.pwd ?}"
  avisos_tarea:
    notify:
      task:
        via:
          - telegram:
              bot_token: "{? telegram.token ?}"
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: "{? telegram.user ?}"

schedules:
  - tasks: [my_tv_series, yts_movies]
    schedule:
      minute: 45
      hour: 7,11,15,19,23


tasks:
  my_tv_series:
    rss: http://showrss.info/user/68577.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    quality:
      - 1080p
    content_size:
      min: 1000
    series:
      - Foundation
  yts_movies:
    rss: https://yts.mx/rss/
    quality:
      - 1080p
    content_size:
      min: 1200
    imdb:
     min_score: 7
     min_votes: 5000
     reject_genres:
       - horror
