variables: variables.yml
templates:
  torrent_server:
    transmission:
      host: localhost
      port: 9091
      username: "{? transmission.usr ?}"
      password: "{? transmission.pwd ?}"
  avisos_tarea:
    notify:
      task:
        via:
          - telegram:
              bot_token: "{? telegram.token ?}"
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: "{? telegram.user ?}"
  template_imdb:
    imdb:
     min_score: 7
     min_votes: 5000
     min_year: 2018
     reject_genres:
       - horror
  movie_quality:
    quality: 
      - 1080p
    content_size:
      min: 1000
  serie_quality:
    quality: 
      - 1080p
    content_size:
      min: 500


tasks:
  my_tv_series:
    template: 
      - torrent_server
      - template_imdb
      - serie_quality
    rss: http://showrss.info/user/68577.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    series:
      - Foundation
  yts_movies:
    template: 
      - torrent_server
      - template_imdb
      - movie_quality
    rss: https://yts.mx/rss/


schedules:
  - tasks: [my_tv_series, yts_movies]
    interval:
      hours: 1
